volumes:
  db: {}
  db_test: {}

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: devmiguelangel/ms-api:latest
    container_name: ms_api
    volumes:
      - ./api:/api
    env_file:
      - ./compose/api.env
    ports:
      - '8001:8001'
    depends_on:
      - db
      - db_test
    restart: unless-stopped

  db:
    image: postgres:16.3-alpine
    container_name: ms_db
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - ./compose/db.env
    ports:
      - '5432:5432'
    restart: unless-stopped

  db_test:
    image: postgres:16.3-alpine
    container_name: ms_db_test
    volumes:
      - db_test:/var/lib/postgresql/data
    env_file:
      - ./compose/db_test.env
    ports:
      - '5433:5432'
    restart: unless-stopped
