name: deploy

on: [push, pull_request]

jobs:
  build:
    environment:
      name: testing
    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_TEST_HOST: ${{ secrets.DB_TEST_HOST }}
      DB_TEST_PORT: ${{ secrets.DB_TEST_PORT }}
      DB_TEST_USER: ${{ secrets.DB_TEST_USER }}
      DB_TEST_PASSWORD: ${{ secrets.DB_TEST_PASSWORD }}
      DB_TEST_NAME: ${{ secrets.DB_TEST_NAME }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      ALGORITHM: ${{ secrets.ALGORITHM }}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}

    services:
      postgres:
        image: postgres:16.3-alpine
        env:
          POSTGRES_USER: ${{ secrets.DB_TEST_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_TEST_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DB_TEST_NAME }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        working-directory: ./api
        run: |
          python -m pip install --upgrade pip
          pip install poetry -v
          poetry install --no-root

      - name: Run lint
        working-directory: ./api
        run: poetry run ruff check

      - name: Run tests
        working-directory: ./api
        run: poetry run pytest

